spring:
  application:
    name: spotlight-time
  datasource:
    url: jdbc:postgresql://${DB_HOST}/${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    generate-ddl: true
server:
  port: ${PORT}
