spring:
  application:
    name: spotlight-time
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost:5432}/${DB_DATABASE:spotlight_time}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:codex}
  jpa:
    generate-ddl: true
server:
  port: ${PORT:9000}
spotlight:
  api:
    fu:
      path: ${API_PATH:/rest/os.psy.research.spotlight.v1.FocusUnitApi}
