spring:
  application:
    name: spotlight-link-flyway
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost:5432}/${DB_DATABASE:spotlight_link}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:codex}
  flyway:
    url: jdbc:postgresql://${DB_HOST:localhost:5432}/${DB_DATABASE:spotlight_link}
    user: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:codex}
    baseline-on-migrate: true
    sql-migration-prefix: V
    repeatable-sql-migration-prefix: R
    sql-migration-separator: __
    sql-migration-suffixes: .sql
  jpa:
    hibernate:
      ddl-auto: validate
